// This file is auto-generated by scripts/generate_auto_import.go - DO NOT EDIT
package main

import (
	_ "catears/ffs/goapp/api/admin"
	_ "catears/ffs/goapp/api/directory"
	_ "catears/ffs/goapp/api/download"
	_ "catears/ffs/goapp/api/file"
	_ "catears/ffs/goapp/api/logout"
	_ "catears/ffs/goapp/api/upload"
	_ "catears/ffs/goapp/api/user-logon"
)
