import { join } from '@std/path/join';

const knownProperties = [
    'textContent',
    'innerHTML',
    'innerText',
];

function myLocation() {
    return new URL('.', import.meta.url).pathname;
}

const outputLocation = join(
    myLocation(),
    '..',
    'app',
    'website',
    'views',
    'templates',
    'html-property-mapper.js',
);

function makePropertySetter(propertyName: string) {
    return `  ${propertyName.toLocaleLowerCase()}: (element, value) => element.${propertyName} = value,`;
}

const prefix = `// This variable is auto-generated by generate-html-property-mapping.ts
const _mappedProperties = {
`;

const mappedProperties = knownProperties.map(makePropertySetter).join('\n');

const postfix = `
};`;

Deno.writeTextFile(outputLocation, prefix + mappedProperties + postfix, {
    append: false,
    create: true,
});
