package main

import (
	"fmt"
	"io/fs"
	"os"
	"path"
	"sort"
	"strings"
)

func GenerateAutoImport() {
	targetFile := path.Join("src", "goapp", "api_auto_import.go")
	apiDir := path.Join("src", "goapp", "api")
	imports := make(map[string]bool)
	fs.WalkDir(os.DirFS("."), apiDir, func(p string, d os.DirEntry, err error) error {
		if strings.HasSuffix(p, ".go") {
			importPath, _ := strings.CutPrefix(p, "src/")
			importPath, _ = strings.CutSuffix(importPath, "/"+path.Base(p))
			importPath = fmt.Sprintf("catears/ffs/%s", importPath)
			imports[importPath] = true
		}
		return nil
	})

	sortedImports := []string{}
	for k := range imports {
		sortedImports = append(sortedImports, k)
	}

	sort.Strings(sortedImports)
	builder := strings.Builder{}
	builder.WriteString(
		`// This file is auto-generated by scripts/generate_auto_import.go - DO NOT EDIT
package main

import (
`)
	for _, importPath := range sortedImports {
		fmt.Fprintf(&builder, "	_ \"%s\"\n", importPath)
	}
	builder.WriteString(
		`)
`)
	os.WriteFile(targetFile, []byte(builder.String()), 0o666)
}
